### ISSUE TITLE
video calibration document - image links

### ISSUE THREAD

**Issue by kieranjol** [pugetsoundandvision/information#1]
Hi,

It looks like the some of the images for your audio guide are in your video calibration guide.. Also thanks for sharing this resource, very helpful!

-K

**Comment by privatezero** [comment]
Oh! Thanks for pointing that out!  That all got exported from google docs and I must have totally forgotten to take a look at it and fix it!!

**Comment by privatezero** [comment]
Fixed!

**Comment by kieranjol** [comment]
Looks great, thanks!
